input:
  generate:
    interval: 1s
    mapping: |
      root.id = uuid_v4()
      root.user.name = fake("first_name")
      root.user.surname = fake("last_name")
      root.user.email = fake("email")
      root.content = fake("paragraph")
pipeline:
  processors:
    - log:
        message: ${! meta() }
    - mapping: |
        root.id = this.id
        root.full_name =  this.user.name + " " + this.user.surname
        root.email = this.user.email
        root.content = this.content
    - log:
        message: \${! json() }
output:
  kafka_franz:
    seed_brokers:
      -  ${RP_BOOTSTRAP_SERVER}
    topic: first_topic
    compression: none
    key: ${! json("id") }             