input:
  label: ""
  kafka_franz:
    seed_brokers:
      - ${RP_BOOTSTRAP_SERVER}
    topics:
      - first_topic
    regexp_topics: false
    consumer_group: "first_group"
pipeline:
  processors:
    - mapping: |
        meta doc = this
        meta content = this.content.string()
        meta key = meta("kafka_key").string()
    - log:
        message: ${! meta() }
    - branch:
        processors:
          - http:
              url: http://my_service:5000/embedding
              verb: POST
              headers:
                Content-Type: application/json
        result_map: |-
          root.embeddings = this.embedding
          root.metadata = metadata("doc").string()
    - log:
        message: ${! json("embeddings") }
output:
  pinecone:
    max_in_flight: 64
    host: ${PINECONE_HOST}
    api_key: ${PINECONE_API_KEY}
    operation: upsert-vectors
    id: ${! metadata("kafka_key").string() }
    vector_mapping: embeddings
    metadata_mapping: |-
      root.content = @.content
      root.full_name = @.doc.full_name.string()
      root.email = @.doc.email.string()
      root.timestamp = timestamp_unix()         